"""Backend protocol for QRICS Python simulation adapters."""

from __future__ import annotations

from typing import Protocol

from qrics.sim.schema import (
    AdapterConfig,
    AdapterResult,
    AdapterState,
    AdapterStepResult,
    ObservationPacket,
    RobotState,
    SafeAction,
    SceneProfile,
)


class SimulationBackend(Protocol):
    def name(self) -> str: ...
    def state(self) -> AdapterState: ...
    def initialize(self, config: AdapterConfig) -> AdapterResult[AdapterState]: ...
    def load_scene(self, scene_profile: SceneProfile) -> AdapterResult[SceneProfile]: ...
    def reset(self) -> AdapterResult[AdapterStepResult]: ...
    def step(self, safe_action: SafeAction) -> AdapterResult[AdapterStepResult]: ...
    def observe(self) -> AdapterResult[ObservationPacket]: ...
    def robot_state(self) -> AdapterResult[RobotState]: ...
    def close(self) -> AdapterResult[AdapterState]: ...
